# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(blank=True, default=None, max_length=48, null=True)),
            ],
        ),
    ]
