# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Team_Name', models.CharField(blank=True, default=None, max_length=48, null=True)),
                ('Characters', models.TextField(blank=True, default=None, max_length=128, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.Country')),
            ],
        ),

    ]
