# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.Country', to_field='name'),
        ),
    ]
