# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_auto_20171021_2340'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX team_fulltext_index ON team_team (Characters)',),
            ('DROP INDEX team_fulltext_index on team_team',)
        ),
    ]
