# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Team', '0001_initial'),
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact_Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Cost', models.IntegerField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer')),
                ('Site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.Site')),
                ('Team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.Team')),
            ],
        ),
    ]
