# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact_sale',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
