# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_auto_20171028_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact_sale',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
